### ISSUE TITLE
Compatibility with Intel NCS2 and OpenVINO

### ISSUE THREAD

**Issue by CBrenz-cmd** [GeniSysAI/Vision#2]
Thank you for this useful implementation of real-time face recognition on the edge!

I would like to ask if there are any plans for introducing compatibility of this program with the Intel Neural Compute Stick 2 and the OpenVINO toolkit, instead of the Movidius NCS and NCSDK?

Thanks and cheers!

**Comment by AdamMiltonBarker** [comment]
Hi thanks, I have restructured these projects quite a lot, TassAI (https://github.com/TassAI) is going to be computer vision side of the GeniSysAI network and this organization will just include the server and the NLU. 

The most up to date versions of GeniSysAI NLU & TassAI Computer Vision are currently in the Leukemia AI Research organization but they are designed for a different network known as HIAS (https://github.com/LeukemiaAiResearch). The TassAI repository in LeukemiaAiResearch has versions of TassAI that use OpenVINO and NCS2 yes. When I get some time I will be updating the TassAI organization and this organization.

I am going to archive this repository now as it actually won't be part of this organization any more.

Hope this helps.
